/var/log/nginx/*.json {
	daily
	rotate 14
	compress
	delaycompress
	missingok
	notifempty
	create 0640 root root
	sharedscripts
	postrotate
		[ -f /run/nginx.pid ] && kill -USR1 "$(cat /run/nginx.pid)"
	endscript
}
