name: qdrant

networks:
  ai-stack:
    external: true

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    environment:
      - QDRANT__TELEMETRY_DISABLED=true
    ports:
      - "${QDRANT_HOST}:${QDRANT_PORT}:6333"
    volumes:
      - /data/persistence/qdrant:/qdrant/storage
    networks:
      - ai-stack

