upstream llama {
    server 127.0.0.1:8082;
}

# Server for llama backend (model inference server)
server {
    listen 80;
    server_name model.cloud.home;

    location / {
        proxy_pass http://llama;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        add_header Access-Control-Allow-Origin * always;
    }
}
