upstream searxng {
    server 127.0.0.1:8888;
}

# Server for SearxNG web search service
server {
    listen 80;
    server_name websearch.cloud.home;

    location / {
        proxy_pass http://searxng;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;

        add_header Access-Control-Allow-Origin * always;
    }
}