#!/usr/bin/env bash
# Emits one Kconfig bool per GPU that rocminfo reports with a real UUID, plus a GPU_ARCHS macro
# (their distinct gfx targets). The symbol name is derived from the UUID so a selection survives
# regeneration; 'make config' reverses it.
set -euo pipefail

echo "# Generated by scripts/gen-gpu-kconfig.sh on every 'make menuconfig' — do not edit."

command -v rocminfo >/dev/null || {
	echo 'GPU_ARCHS :='
	echo 'comment "rocminfo not found — use the manual field below"'
	exit 0
}

rocminfo 2>/dev/null | awk '
	/^ *Name:/ && $2 ~ /^gfx/ { arch = $2; next }
	/^ *Uuid:/ { uuid = $2; next }
	/^ *Marketing Name:/ && uuid ~ /^GPU-[0-9A-Fa-f]+$/ {
		sub(/^ *Marketing Name: */, ""); sub(/ *$/, ""); gsub(/"/, "\\\"")
		hex = toupper(substr(uuid, 5))
		body = body sprintf("\nconfig GPU_DEVICE_%s\n\tbool \"%s (%s, %s)\"\n\tdefault y\n", hex, $0, uuid, arch)
		if (!(arch in seen)) { seen[arch]; archs = archs (archs ? ";" : "") arch }
		uuid = ""
	}
	END { printf "GPU_ARCHS := %s\n%s", archs, body }
'
