services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - "127.0.0.1:8888:8080"
    volumes:
      - ./config:/etc/searxng
    restart: unless-stopped
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888
    dns:
      - 1.1.1.1
