name: monitoring

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    pid: host
    network_mode: host
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --path.rootfs=/rootfs
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
      - --no-collector.xfs

  amd-device-metrics:
    image: rocm/device-metrics-exporter:v1.1.0
    container_name: amd-device-metrics
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
